

#ifndef __APP_defines_H__
#define __APP_defines_H__




#define MAX_LANGUAGES	3
#define L_ESPANOL	0
#define L_INGLES	1
#define L_ITALIANO	2
#define DEFAULT_LANGUAGE	L_ITALIANO

#define PAIS_ESPANA		0
#define PAIS_PORTUGAL	1
#define PAIS_ITALIA		2
#define USE_LOADED		3
#define BASE_COUNTRY	USE_LOADED


extern const char * const TEXTS[][MAX_LANGUAGES];
typedef enum{
	TXT_NO = 0,
	TXT_SI,
	TXT_GUARDAR___,
	TXT_BORRAR_,
	TXT_GUARDAR_CAMBIOS,
	TXT_MENU_PULSE_OK,
	TIT_MENU,				
	TIT_EQUIPOS,			
	TIT_CONFIGURACION,		
	TIT_LOCALIZACION,			
	TIT_CAPTURA_GPS,	
	TIT_LOCALIZ_GUARDADA,
	TIT_IDIOMA,
	TIT_HORAFECHA,
	TIT_BORRAR_MEMORIA,
	TIT_CONTRASTE,
	TIT_LEER_EQUIPO,
	TIT_VOLCAR_EQUIPO,
	TIT_SALVAR_EQUIPO,
	TIT_EQUIPOS_GUARDADOS,
	TIT_LUGARES_GUARDADOS
}E_TextCodes;

extern const char * const LSTBOX[][MAX_LANGUAGES];
typedef enum{
	LBX_MENU = 0,
	LBX_EQUIPOS,
	LBX_CONFIGURACION,		
	LBX_LOCALIZACION,			
	LBX_IDIOMA,
	LBX_BORRAR_MEMORIA,
}E_ListboxCodes;



#endif
